### ISSUE TITLE
Cannot run score_texts_emojis.py

### ISSUE THREAD

**Issue by DavidRayner** [huggingface/torchMoji#14]
I get a few errors when I run `score_text_emojis.py`
I'm using `pytorch-cpu=0.4.0=py35_cpu_1` and master of torchMoji (b3dd91958ba2a752e0fdee2fd1839ae2bbea549a)

It seems the errors are caused by changes to PyTorch.

e.g.
```
$ python score_texts_emojis.py

Tokenizing using dictionary from /home/dev/Downloads/torchMoji/model/vocabulary.json
Loading model from /home/dev/Downloads/torchMoji/model/pytorch_model.bin.
/home/dev/Downloads/torchMoji/torchmoji/model_def.py:159: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  nn.init.uniform(self.embed.weight.data, a=-0.5, b=0.5)
/home/dev/Downloads/torchMoji/torchmoji/model_def.py:161: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  nn.init.xavier_uniform(t)
/home/dev/Downloads/torchMoji/torchmoji/model_def.py:163: UserWarning: nn.init.orthogonal is now deprecated in favor of nn.init.orthogonal_.
  nn.init.orthogonal(t)
/home/dev/Downloads/torchMoji/torchmoji/model_def.py:165: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  nn.init.constant(t, 0)
/home/dev/Downloads/torchMoji/torchmoji/model_def.py:167: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  nn.init.xavier_uniform(self.output_layer[0].weight.data)
TorchMoji(
  (embed): Embedding(50000, 256)
  (embed_dropout): Dropout2d(p=0)
  (lstm_0): LSTMHardSigmoid(256, 512, batch_first=True, bidirectional=True)
  (lstm_1): LSTMHardSigmoid(1024, 512, batch_first=True, bidirectional=True)
  (attention_layer): Attention(2304, return attention=False)
  (final_dropout): Dropout(p=0)
  (output_layer): Sequential(
    (0): Linear(in_features=2304, out_features=64, bias=True)
    (1): Softmax()
  )
)
Running predictions.
Traceback (most recent call last):
  File "score_texts_emojis.py", line 48, in <module>
    prob = model(tokenized)
  File "/home/dev/miniconda3/envs/hub/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dev/Downloads/torchMoji/torchmoji/model_def.py", line 218, in forward
    packed_input = PackedSequence(data=x, batch_sizes=packed_input.batch_sizes)
TypeError: __new__() got an unexpected keyword argument 'data'
```

---

I have got the example running after the following modifications:

* Need to remove argument names from calls to PackedSequence.

https://github.com/huggingface/torchMoji/blob/b3dd91958ba2a752e0fdee2fd1839ae2bbea549a/torchmoji/model_def.py#L218

Change to `packed_input = PackedSequence(x, packed_input.batch_sizes)`

https://github.com/huggingface/torchMoji/blob/b3dd91958ba2a752e0fdee2fd1839ae2bbea549a/torchmoji/model_def.py#L226-L229

Change to:
``` python
        packed_input = PackedSequence(torch.cat((lstm_1_output.data,
                                                 lstm_0_output.data,
                                                 packed_input.data), dim=1),
                                      packed_input.batch_sizes)
```

* Cannot reverse batch_sizes.

https://github.com/huggingface/torchMoji/blob/b3dd91958ba2a752e0fdee2fd1839ae2bbea549a/torchmoji/lstm.py#L266

Change to `for batch_size in reversed(list(batch_sizes)):`

**Comment by thomwolf** [comment]
Hi, this should be fixed by #15, thanks to @SsnL!
